apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-alerts
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kubrakus/prometheus-stack-repo.git
    targetRevision: main
    path: alerts
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
